northern_wind_120:
  sku: "BB-NW120-ARGB-001"
  full_name: "Northern Wind 120mm ARGB 5 Fan Bundle"
  short_name: "Northern Wind 120"
  html_name: "<span class='orbitron notranslate'>NORTHERN WIND 120</span>"
  price_gbp: 39.99
  warranty_enabled: true
  manual_enabled: true
  product_type: "fan_kit"
  release_date: "TBA"
  variants:
    - black
    - white
  specs:
    airflow: "58 CFM"
    static_pressure: "1.3 mmH2O"
    noise: "19-29 dBA"
    bearing: "Hydraulic"
    leds: "24"
    rpm: "800-1600 RPM"
  thumbnail: "/images/products/northern_wind_120.png"
  warranty_length: "2 years"
  ukca: true
  status: "Prototype Phase"
  product_visible: true
  description: "A complete cooling and lighting upgrade in one kit. Quiet 120mm PWM ARGB fans, an included hub, and honest performance that will keep your system cooled and running at peak efficiency."
  features:
    - "5x <span class='orbitron notranslate'>NORTHERN WIND 120</span>mm PWM ARGB fans"
    - "Included Magnetic ARGB hub"
    - "Silent Operation"
  amazon_url: "https://amazon.co.uk"
  warranty_length: "2-Year Warranty"
  featured: true
  # Future Shopify wiring (leave blank for now)
  shopify_product_id: 
  shopify_default_variant_id: 
  images:
    - /images/products/nw120/main.webp
    - /images/products/nw120/angle.webp
    - /images/products/nw120/rear.webp
    - /images/products/nw120/lighting.webp
  box_contents:
    - 5x <span class='orbitron notranslate'>NORTHERN WIND 120</span>mm ARGB Fans
    - Mounting Screw Set
    - Magnetic Backed Fan Hub
    - Accessories Bundle
    - Product Manual
    - 3x Decal Stickers
    - Thank You Card
  stock_status: out_of_stock
  ships_from: UK
  compatibility:
    - PWM 4-pin headers
    - 5V 3-pin ARGB (ASUS / MSI / Gigabyte)
    - Windows & Linux compatible
  faq:
    - question: Is this compatible with my motherboard?
    - answer: Yes — any standard 4-pin PWM header is supported.
  related:
    - pwm_splitter
    - argb_hub
  badges:
    - PWM
    - ARGB
    - Silent
  use_case: >
    Ideal for airflow-focused builds, compact mid-towers,
    and quiet performance systems where cooling efficiency matters.
  stats:
    Airflow: "58 CFM"
    Noise: "≤ 29 dBA"
    Speed: "800–1600 RPM"
  



  
template_product:
  sku: ""
  full_name: ""
  short_name: ""
  html_name: "<span class='orbitron notranslate'></span>"
  price_gbp: 39.99
  warranty_enabled: false
  manual_enabled: false
  product_type: ""
  release_date: "YYYY-MM-DD"
  variants:
    - variant1
    - variant2
  specs:
    airflow: " CFM"
    static_pressure: " mmH2O"
    noise: " dBA"
    bearing: ""
    leds: ""
    rpm: " RPM"
  thumbnail: "/images/products/template_product.png"
  warranty_length: "2 years"
  ukca: true
  status: "Launch Pricing Soon"
  product_visible: false
  description: ""
  features:
    - ""
    - ""
    - ""
  amazon_url: "https://amazon.co.uk"
  warranty_length: "2-Year Warranty"
  featured: false
  # Future Shopify wiring (leave blank for now)
  shopify_product_id: 
  shopify_default_variant_id: 
