northern_wind_120:
  sku: "BB-NW120-ARGB-001"
  full_name: "Northern Wind 120mm ARGB Fan Bundle"
  short_name: "Northern Wind"
  warranty_enabled: true
  manual_enabled: true
  product_type: "fan_kit"
  release_date: "2025-11-01"
  variants:
    - black
    - white
  specs:
    airflow: "58 CFM"
    static_pressure: "1.3 mmH2O"
    noise: "19-29 dBA"
    bearing: "Hydraulic"
    leds: "24"
    rpm: "800-1600 RPM"
  thumbnail: "/images/products/northern_wind_120.png"
  warranty_length: "2 years"

template_product:
  sku: "SKU-HERE"
  full_name: "Template Product"
  short_name: "Template"
  warranty_enabled: false
  manual_enabled: false
  product_type: "fan_kit"
  release_date: "YYYY-MM-DD"
  variants:
    - variant_a
    - variant_b
  specs:
    airflow: ""
    static_pressure: ""
    noise: ""
    bearing: ""
    leds: ""
    rpm: ""
