northern_wind_120:
  sku: "BB-NW120-ARGB-001"
  full_name: "Northern Wind 120mm ARGB Fan Bundle"
  short_name: "Northern Wind 120"
  html_name: "<span class='orbitron notranslate'>NORTHERN WIND 120</span>"
  price_gbp: 39.99
  warranty_enabled: true
  manual_enabled: true
  product_type: "fan_kit"
  release_date: "2025-11-01"
  variants:
    - black
    - white
  specs:
    airflow: "58 CFM"
    static_pressure: "1.3 mmH2O"
    noise: "19-29 dBA"
    bearing: "Hydraulic"
    leds: "24"
    rpm: "800-1600 RPM"
  thumbnail: "/images/products/northern_wind_120.png"
  warranty_length: "2 years"
  ukca: true
  status: "Launch Pricing Soon"
  product_visible: true
  description: "A complete cooling and lighting upgrade in one kit. Quiet 120mm PWM ARGB fans, an included hub, and honest performance."
  features:
    - "5x 120mm NORTHERN WIND PWM ARGB fans"
    - "Included ARGB hub"
    - "Static-pressure airflow design"
  amazon_url: "https://amazon.co.uk"
  warranty_length: "2-Year Warranty"
  featured: true
  # Future Shopify wiring (leave blank for now)
  shopify_product_id: 
  shopify_default_variant_id: 
  
template_product:
  sku: ""
  full_name: ""
  short_name: ""
  html_name: "<span class='orbitron notranslate'></span>"
  price_gbp: 39.99
  warranty_enabled: false
  manual_enabled: false
  product_type: ""
  release_date: "YYYY-MM-DD"
  variants:
    - variant1
    - variant2
  specs:
    airflow: " CFM"
    static_pressure: " mmH2O"
    noise: " dBA"
    bearing: ""
    leds: ""
    rpm: " RPM"
  thumbnail: "/images/products/template_product.png"
  warranty_length: "2 years"
  ukca: true
  status: "Launch Pricing Soon"
  product_visible: false
  description: ""
  features:
    - ""
    - ""
    - ""
  amazon_url: "https://amazon.co.uk"
  warranty_length: "2-Year Warranty"
  featured: false
  # Future Shopify wiring (leave blank for now)
  shopify_product_id: 
  shopify_default_variant_id: 
