northern_wind_120:
  warranty_enabled: true
  full_name: "Northern Wind 120mm ARGB Fan Bundle"
  short_name: "Northern Wind"
  manual_enabled: true
  product_type: "fan_kit"
  release_date: "2025-11-01"
